# Drehort-Daten 4 Blocks (TNT Serie, 2017–2019). Koordinaten: geocode.json (Nominatim) bzw. OSM-Geometrie.
MV='https://mitvergnuegen.com/2018/11-drehorte-aus-4-blocks-die-ihr-besuchen-koennt'
SB='https://sbahn.berlin/was-hast-du-vor/neues-entdecken/artikel/4-blocks-diese-drehorte-muesst-ihr-kennen/'
YV='https://yovie.de/drehorte-berlin/'
UH='https://unserhavelland.de/2019/06/03/dreharbeiten-fuer-4-blocks-clan-machenschaften-in-brieselang/'
S={'mv':['Mit Vergnügen',MV],'sb':['S-Bahn Berlin',SB],'yv':['yovie',YV],'uh':['Unser Havelland',UH]}

# kat: clan | revier | justiz | glamour | kiez | umland
ORTE=[
 dict(id='highdeck',n='High-Deck-Siedlung',kat='clan',geo='pt:highdeck',radius=260,kiez='Neukölln',
      adr='Michael-Bohnen-Ring / Sonnenallee, 12057 Berlin',st='S Köllnische Heide',
      rolle='Die markante Großsiedlung der 1970er mit ihren Hochdeck-Laubengängen über der Straße. Hier wurde die spektakuläre Polizei-Razzia der ersten Folge gedreht.',
      tipp='Die Siedlung wird wegen der Serie oft als die „echten 4 Blocks“ bezeichnet. Rund 6.000 Menschen wohnen hier, bitte Rücksicht nehmen.',
      fig=['Toni','Latif'],staffel='S1',q=['yv','mv','sb']),
 dict(id='sonnenallee',n='Sonnenallee',kat='kiez',geo='street:Sonnenallee',clip=[None,13.462],kiez='Neukölln',
      adr='Sonnenallee, zwischen Hermannplatz und Estrel',st='U Hermannplatz · S Sonnenallee',
      rolle='Die Lebensader des Hamady-Reviers. Sie zieht sich durch die gesamte Serie und ist prominent im Intro jeder Folge zu sehen.',
      tipp='Am besten zu Fuß vom Hermannplatz Richtung Südosten, mit Stopp bei einer der vielen arabischen Bäckereien.',
      fig=['Toni','Abbas'],staffel='S1–S3',q=['sb']),
 dict(id='blackwhite',n='Black White',kat='clan',geo='pt:blackwhite',kiez='Neukölln',
      adr='Sonnenallee 72, 12045 Berlin',st='U Rathaus Neukölln',
      rolle='Straßenlokal an der Sonnenallee, an dem der Clan seine alltäglichen Geschäfte abwickelt.',
      fig=['Toni','Abbas'],staffel='S1',q=['mv']),
 dict(id='elsalam',n='Bäckerei El Salam',kat='clan',geo='pt:elsalam',kiez='Neukölln',
      adr='Wildenbruchstraße 68, 12045 Berlin',st='U Rathaus Neukölln',
      rolle='Die echte arabische Bäckerei ist Treffpunkt des Clans: Hier werden Geschäfte besprochen und Baklava gegessen. Vince trifft hier Amara, die beiden trinken zusammen Tee.',
      tipp='Die Bäckerei ist in Betrieb, also: einfach reingehen und Baklava probieren.',
      alt='Adresse in den Quellen uneinheitlich: Wildenbruchstraße 68 (Mit Vergnügen, S-Bahn) bzw. Wildenbruchstraße 8 (yovie); auch Haberstraße 7 wird genannt.',
      fig=['Vince','Amara'],staffel='S1',q=['mv','sb','yv']),
 dict(id='stuttgarter',n='Wohnung der Hamadys',kat='clan',geo='pt:stuttgarter',kiez='Neukölln',
      adr='Stuttgarter Straße 47, 12059 Berlin',st='S+U Neukölln',
      rolle='Außenaufnahmen für das Zuhause der Familie Hamady, Schauplatz vieler zentraler Wendungen der Handlung.',
      tipp='Privates Wohnhaus, nur von der Straße aus ansehen.',
      fig=['Toni','Kalila'],staffel='S1–S3',q=['mv']),
 dict(id='teppich',n='Teppichladen',kat='clan',geo='corner:Fuldastraße|Donaustraße',kiez='Neukölln',
      adr='Fuldastraße, Ecke Donaustraße, 12045 Berlin',st='U Rathaus Neukölln',
      rolle='Ein weiterer wichtiger Schauplatz im Kiez nahe dem Rathaus Neukölln, vor allem für Außenaufnahmen.',
      fig=['Toni'],staffel='S1',q=['sb']),
 dict(id='rathaus',n='Rathaus Neukölln',kat='kiez',geo='pt:rathaus',kiez='Neukölln',
      adr='Karl-Marx-Straße 83, 12043 Berlin',st='U Rathaus Neukölln',
      rolle='Das Rathaus mit seinem Turm liefert die Establishing Shots zum Auftakt: So weiß man sofort, wo man ist.',
      fig=[],staffel='S1',q=['sb']),
 dict(id='kms',n='Karl-Marx-Straße',kat='kiez',geo='street:Karl-Marx-Straße',kiez='Neukölln',
      adr='Karl-Marx-Straße, Hermannplatz bis S Neukölln',st='U Karl-Marx-Straße · S+U Neukölln',
      rolle='Zahlreiche Außen- und Straßenszenen, die das authentische Kiez-Gefühl einfangen, samt türkischer Bäckereien.',
      fig=[],staffel='S1–S3',q=['sb']),
 dict(id='hermannstr',n='Hermannstraße',kat='kiez',geo='street:Hermannstraße',kiez='Neukölln',
      adr='Hermannstraße, Hermannplatz bis S Hermannstraße',st='U Boddinstraße · S+U Hermannstraße',
      rolle='Weitere Außenaufnahmen für den Straßenalltag in Neukölln.',
      fig=[],staffel='S1–S3',q=['sb']),
 dict(id='hasenheide',n='Volkspark Hasenheide',kat='revier',geo='area:Volkspark Hasenheide',kiez='Neukölln',
      adr='Hasenheide, 10967 Berlin',st='U Hermannplatz',
      rolle='Dealer-Revier im Park, wie in der Wirklichkeit ein bekannter Umschlagplatz.',
      fig=['Zeki','Issam'],staffel='S1',q=['sb']),
 dict(id='estrel',n='Estrel Berlin',kat='glamour',geo='pt:estrel',kiez='Neukölln',
      adr='Sonnenallee 225, 12057 Berlin',st='S Sonnenallee',
      rolle='Deutschlands größtes Hotel ist Kulisse für illegale Pokerrunden und Clan-Treffen. Beim Pokerspiel gerät Toni unter Druck.',
      fig=['Toni'],staffel='S1',q=['yv','mv']),
 dict(id='private',n='Private Center Berlin',kat='justiz',geo='pt:private',kiez='Britz',
      adr='Britzer Damm 115, 12347 Berlin',st='U Blaschkoallee',
      rolle='Ausgerechnet ein Erotikkino: Hier trifft sich der verdeckte Ermittler Vince heimlich mit seinen Kontaktleuten von der Polizei.',
      fig=['Vince'],staffel='S1',q=['mv']),
 dict(id='kotti',n='Kottbusser Tor · Café Kotti',kat='revier',geo='pt:kotti',kiez='Kreuzberg',
      adr='Adalbertstraße 96 (Neues Kreuzberger Zentrum), 10999 Berlin',st='U Kottbusser Tor',
      rolle='Das Zentrum Kreuzbergs ist ein zentraler Handlungsort. Im Neuen Kreuzberger Zentrum liegt Vince’ Wohnung, im Café Kotti fliegt seine Tarnung als Undercover-Polizist auf.',
      tipp='Das Café Kotti im ersten Stock des NKZ ist ein echtes Café mit Blick auf den Platz.',
      fig=['Vince'],staffel='S1',q=['mv','sb','yv']),
 dict(id='goerli',n='Görlitzer Park',kat='revier',geo='area:Görlitzer Park',kiez='Kreuzberg',
      adr='Görlitzer Straße, 10997 Berlin',st='U Görlitzer Bahnhof · U Schlesisches Tor',
      rolle='Der „Görli“ ist das Revier der jüngeren Clan-Mitglieder Zeki und Issam für ihre Drogengeschäfte. Issam verliebt sich hier.',
      fig=['Zeki','Issam'],staffel='S1',q=['mv','sb','yv']),
 dict(id='daimler',n='Daimler Contemporary',kat='glamour',geo='pt:daimler',kiez='Tiergarten',
      adr='Alte Potsdamer Straße 5 (Haus Huth), 10785 Berlin',st='S+U Potsdamer Platz',
      rolle='Edle Kulisse im modernen Berlin: Auf der Dachterrasse finden geheime Treffen mit Lieferanten statt.',
      fig=['Toni'],staffel='S1',q=['mv','sb']),
 dict(id='jva',n='JVA Moabit',kat='justiz',geo='pt:jva',kiez='Moabit',
      adr='Alt-Moabit 12a, 10559 Berlin',st='U Turmstraße · S+U Hauptbahnhof',
      rolle='Tonis Schwager Latif landet hier nach der Razzia mit Kokain in Untersuchungshaft.',
      fig=['Latif'],staffel='S1',q=['mv']),
 dict(id='amtsgericht',n='Amtsgericht Tiergarten',kat='justiz',geo='pt:amtsgericht',kiez='Moabit',
      adr='Turmstraße 91, 10559 Berlin (Kriminalgericht Moabit)',st='U Turmstraße',
      rolle='Gerichtsszenen im wuchtigen Kriminalgericht: Abbas muss sich hier wegen Mordes verantworten.',
      alt='Mit Vergnügen nennt Turmstraße 92; das Gerichtsgebäude trägt die Hausnummer 91.',
      fig=['Abbas'],staffel='S2',q=['mv']),
 dict(id='brieselang',n='Gasthaus & Bahnhof Brieselang',kat='umland',geo='pt:brieselang',kiez='Brieselang (Havelland)',
      adr='Platz des Friedens 1, 14656 Brieselang',st='Bahnhof Brieselang (Regionalbahn ab Berlin-Spandau)',
      rolle='Für die dritte und letzte Staffel drehte das Team am 3. Juni 2019 im Gasthaus am Bahnhof Brieselang: drinnen eine Szene mit einem Eisbecher, draußen am Bahnhof zwei weitere Szenen, darunter eine Raucherszene. Vor der Kamera stand Kida Khodr Ramadan als Toni Hamady.',
      tipp='Das Gasthaus ist ein ganz normales Restaurant direkt am Bahnhof, rund 20 Minuten westlich von Spandau.',
      fig=['Toni'],staffel='S3',q=['uh']),
]

# Figuren (Besetzung laut Wikipedia), kurz = Chip-Beschriftung
FIG={
 'Toni':dict(name='Ali „Toni“ Hamady',actor='Kida Khodr Ramadan',rolle='Oberhaupt des Hamady-Clans',
   bio='Toni will raus aus dem Clan und ein legales Leben führen, wird aber immer wieder in die Geschäfte hineingezogen. In Staffel 2 steigt er ins Immobiliengeschäft ein, in Staffel 3 kämpft er nach dem Tod seiner Frau um das Sorgerecht für seine Tochter.'),
 'Vince':dict(name='Vince Kerner',actor='Frederick Lau',rolle='Jugendfreund und verdeckter Ermittler',
   bio='Vince ist Tonis alter Jugendfreund und gewinnt sein Vertrauen. In Wahrheit ist er ein verdeckter Ermittler der Polizei, der sich in den Clan einschleust.'),
 'Abbas':dict(name='Abbas Hamady',actor='Veysel Gelin',rolle='Tonis jüngerer Bruder',
   bio='Abbas ist Tonis jüngerer Bruder und unberechenbar. In Staffel 2 steht er wegen Mordes vor Gericht.'),
 'Latif':dict(name='Latif Hamady',actor='Massiv',rolle='Organisiert das Drogengeschäft',
   bio='Latif ist mit Tonis Schwester Amara verheiratet und organisiert das Drogengeschäft der Familie. Nach einer Razzia landet er in Untersuchungshaft.'),
 'Amara':dict(name='Amara Hamady',actor='Almila Bagriacik',rolle='Schwester von Toni und Abbas',
   bio='Amara ist die Schwester von Toni und Abbas und mit Latif verheiratet.'),
 'Kalila':dict(name='Kalila Hamady',actor='Maryam Zaree',rolle='Tonis Frau',
   bio='Kalila ist Tonis Frau. In Staffel 2 wird sie schwer verletzt, ihr Tod prägt Staffel 3.'),
 'Zeki':dict(name='Zeki',actor='Rauand Taleb',rolle='Drogenläufer',
   bio='Zeki gehört zu den jungen Läufern des Clans und dealt im Görlitzer Park.'),
 'Issam':dict(name='Issam',actor='Emilio Sakraya',rolle='Drogenläufer',
   bio='Issam dealt zusammen mit Zeki im Görlitzer Park und verliebt sich dort.'),
 'Kutscha':dict(name='Hagen Kutscha',actor='Oliver Masucci',rolle='Leiter der Polizeiermittlungen',
   bio='Hagen Kutscha leitet die Ermittlungen der Polizei gegen den Clan.'),
 'Ruffi':dict(name='Rainer „Ruffi“ Ruff',actor='Ronald Zehrfeld',rolle='Präsident eines Rockerclubs',
   bio='Ruffi ist Präsident eines Rockerclubs, mit dem der Clan aneinandergerät.'),
}
KAT={
 'clan':['Clan & Familie','--k-clan'],
 'revier':['Reviere','--k-revier'],
 'justiz':['Polizei & Justiz','--k-justiz'],
 'glamour':['Deals in feiner Kulisse','--k-glamour'],
 'kiez':['Straßen & Kiez','--k-kiez'],
 'umland':['Außerhalb Berlins','--k-umland'],
}
# Neukölln-Rundgang, zu Fuß
TOUR=['rathaus','teppich','blackwhite','elsalam','stuttgarter','estrel','highdeck']

# Fotos von Wikimedia Commons: Ort -> [Dateiname, 1 = zeigt den Drehort selbst / 0 = Umgebung]
FOTOS={
 'highdeck':['High-Deck-Siedlung Berlin-Neukölln 01.jpg',1],
 'sonnenallee':['Sonnenallee Berlin-Neukölln 2020-06-26 01.jpg',1],
 'blackwhite':['Sonnenallee Berlin-Neukölln 2020-06-26 02.jpg',0],
 'elsalam':['Neukölln Wildenbruchstraße.JPG',0],
 'stuttgarter':['Neukölln Stuttgarter Straße.JPG',0],
 'teppich':['Berlin-Neukölln, Fuldastraße.JPG',0],
 'rathaus':['Berlin Neukoelln Rathaus asv2021-03 img1.jpg',1],
 'kms':['Karl-Marx-Straße, Berlin-Neukölln, Bild 1.jpg',1],
 'hermannstr':['Berlin Neukoelln 10Hermannstrasse.JPG',1],
 'hasenheide':['Volkspark Hasenheide.jpg',1],
 'estrel':['Berlin Estrel Neukölln asv2023-11.jpg',1],
 'private':['Britzer Damm - Wohnblock - geo.hlipp.de - 35492.jpg',0],
 'kotti':['Cafe-kotti adalbertstr-96 von der brücke aus 2023-09-03.png',1],
 'goerli':['Görlitzer Park, Berlin.jpg',1],
 'daimler':['Berlin - Weinhaus Huth.jpg',1],
 'jva':['Berlin Jail Moabit Front Dec 2004b.jpg',1],
 'amtsgericht':['Berlin-Kriminalgericht Moabit-Turmstr-Nr91-08-2023-gje.jpg',1],
 'brieselang':['Bahnhof Brieselang.jpg',1],
}

# ---- Serien-Konfiguration (Texte, Kartenausschnitt, Speicher-Namen) ----
META=dict(
  slug='4blocks', short='4 Blocks',
  title='4 Blocks Drehorte Berlin', h1='4 Blocks', h1b='Drehorte',
  eyebrow='TNT Serie · 2017–2019 · Berlin',
  intro='Schauplätze der Clan-Serie um Toni Hamady, von der Sonnenallee bis nach Brieselang.',
  description='Die Berliner Drehorte der Serie 4 Blocks auf einer Karte, mit Szenen, Fotos und Neukölln-Rundgang.',
  credit='4 Blocks (TNT Serie / Wiedemann &amp; Berg Television)',
  note='Einige Orte sind Privathäuser oder Wohnsiedlungen. Bitte nur von der Straße aus ansehen und die Bewohner in Ruhe lassen.',
  sources=[[S[k][0],S[k][1]] for k in ('mv','sb','yv','uh')],
  tourTab='Neukölln-Rundgang', tourTitle='Durch Tonis Revier',
  tourIntro='Ein Spaziergang vom Rathaus Neukölln über Sonnenallee, Weserkiez und Estrel bis zur High-Deck-Siedlung. Start an der U7 Rathaus Neukölln, Ende an der S Köllnische Heide.',
  store='4b', idb='4blocks',          # Namen für den Speicher im Browser (nie ändern, sonst sind Daten weg)
  lat=52.49,                          # Breitengrad für Entfernungsrechnung
  bbox='52.445,13.340,52.532,13.480', # Basiskarte (S,W,N,O)
  extra_bboxes=['52.574,12.982,52.592,13.024'],  # kleine Zusatzausschnitte, z. B. Brieselang
  walk_bbox='52.456,13.422,52.494,13.488',       # Fußwegenetz für den Rundgang
  maxBounds=[[52.435,12.95],[52.60,13.50]],
  admin_label=['Neukölln','Friedrichshain-Kreuzberg','Mitte','Tempelhof-Schöneberg'],
  root=True,                          # Handy-App unter docs/ (sonst docs/<slug>/)
)
