# Drehort-Daten 4 Blocks (TNT Serie, 2017–2019). Koordinaten: geocode.json (Nominatim) bzw. OSM-Geometrie.
MV='https://mitvergnuegen.com/2018/11-drehorte-aus-4-blocks-die-ihr-besuchen-koennt'
SB='https://sbahn.berlin/was-hast-du-vor/neues-entdecken/artikel/4-blocks-diese-drehorte-muesst-ihr-kennen/'
YV='https://yovie.de/drehorte-berlin/'
S={'mv':['Mit Vergnügen',MV],'sb':['S-Bahn Berlin',SB],'yv':['yovie',YV]}

# kat: clan | revier | justiz | glamour | kiez
ORTE=[
 dict(id='highdeck',n='High-Deck-Siedlung',kat='clan',geo='pt:highdeck',radius=260,kiez='Neukölln',
      adr='Michael-Bohnen-Ring / Sonnenallee, 12057 Berlin',st='S Köllnische Heide',
      rolle='Die markante Großsiedlung der 1970er mit ihren Hochdeck-Laubengängen über der Straße. Hier wurde die spektakuläre Polizei-Razzia der ersten Folge gedreht.',
      tipp='Die Siedlung wird wegen der Serie oft als die „echten 4 Blocks“ bezeichnet. Rund 6.000 Menschen wohnen hier, bitte Rücksicht nehmen.',
      fig=['Toni','Latif'],staffel='S1',q=['yv','mv','sb']),
 dict(id='sonnenallee',n='Sonnenallee',kat='kiez',geo='street:Sonnenallee',kiez='Neukölln',
      adr='Sonnenallee, zwischen Hermannplatz und Estrel',st='U Hermannplatz · S Sonnenallee',
      rolle='Die Lebensader des Hamady-Reviers. Sie zieht sich durch die gesamte Serie und ist prominent im Intro jeder Folge zu sehen.',
      tipp='Am besten zu Fuß vom Hermannplatz Richtung Südosten, mit Stopp bei einer der vielen arabischen Bäckereien.',
      fig=['Toni','Abbas'],staffel='S1–S3',q=['sb']),
 dict(id='blackwhite',n='Black White',kat='clan',geo='pt:blackwhite',kiez='Neukölln',
      adr='Sonnenallee 72, 12045 Berlin',st='U Rathaus Neukölln',
      rolle='Straßenlokal an der Sonnenallee, an dem der Clan seine alltäglichen Geschäfte abwickelt.',
      fig=['Toni','Abbas'],staffel='S1',q=['mv']),
 dict(id='elsalam',n='Bäckerei El Salam',kat='clan',geo='pt:elsalam',kiez='Neukölln',
      adr='Wildenbruchstraße 68, 12045 Berlin',st='U Rathaus Neukölln',
      rolle='Die echte arabische Bäckerei ist Treffpunkt des Clans: Hier werden Geschäfte besprochen und Baklava gegessen. Vince trifft hier Amara, die beiden trinken zusammen Tee.',
      tipp='Die Bäckerei ist in Betrieb, also: einfach reingehen und Baklava probieren.',
      alt='Adresse in den Quellen uneinheitlich: Wildenbruchstraße 68 (Mit Vergnügen, S-Bahn) bzw. Wildenbruchstraße 8 (yovie); auch Haberstraße 7 wird genannt.',
      fig=['Vince','Amara'],staffel='S1',q=['mv','sb','yv']),
 dict(id='stuttgarter',n='Wohnung der Hamadys',kat='clan',geo='pt:stuttgarter',kiez='Neukölln',
      adr='Stuttgarter Straße 47, 12059 Berlin',st='S+U Neukölln',
      rolle='Außenaufnahmen für das Zuhause der Familie Hamady, Schauplatz vieler zentraler Wendungen der Handlung.',
      tipp='Privates Wohnhaus, nur von der Straße aus ansehen.',
      fig=['Toni','Kalila'],staffel='S1–S3',q=['mv']),
 dict(id='teppich',n='Teppichladen',kat='clan',geo='corner:Fuldastraße|Donaustraße',kiez='Neukölln',
      adr='Fuldastraße, Ecke Donaustraße, 12045 Berlin',st='U Rathaus Neukölln',
      rolle='Ein weiterer wichtiger Schauplatz im Kiez nahe dem Rathaus Neukölln, vor allem für Außenaufnahmen.',
      fig=['Toni'],staffel='S1',q=['sb']),
 dict(id='rathaus',n='Rathaus Neukölln',kat='kiez',geo='pt:rathaus',kiez='Neukölln',
      adr='Karl-Marx-Straße 83, 12043 Berlin',st='U Rathaus Neukölln',
      rolle='Das Rathaus mit seinem Turm liefert die Establishing Shots zum Auftakt: So weiß man sofort, wo man ist.',
      fig=[],staffel='S1',q=['sb']),
 dict(id='kms',n='Karl-Marx-Straße',kat='kiez',geo='street:Karl-Marx-Straße',kiez='Neukölln',
      adr='Karl-Marx-Straße, Hermannplatz bis S Neukölln',st='U Karl-Marx-Straße · S+U Neukölln',
      rolle='Zahlreiche Außen- und Straßenszenen, die das authentische Kiez-Gefühl einfangen, samt türkischer Bäckereien.',
      fig=[],staffel='S1–S3',q=['sb']),
 dict(id='hermannstr',n='Hermannstraße',kat='kiez',geo='street:Hermannstraße',kiez='Neukölln',
      adr='Hermannstraße, Hermannplatz bis S Hermannstraße',st='U Boddinstraße · S+U Hermannstraße',
      rolle='Weitere Außenaufnahmen für den Straßenalltag in Neukölln.',
      fig=[],staffel='S1–S3',q=['sb']),
 dict(id='hasenheide',n='Volkspark Hasenheide',kat='revier',geo='area:Volkspark Hasenheide',kiez='Neukölln',
      adr='Hasenheide, 10967 Berlin',st='U Hermannplatz',
      rolle='Dealer-Revier im Park, wie in der Wirklichkeit ein bekannter Umschlagplatz.',
      fig=['Zeki','Issam'],staffel='S1',q=['sb']),
 dict(id='estrel',n='Estrel Berlin',kat='glamour',geo='pt:estrel',kiez='Neukölln',
      adr='Sonnenallee 225, 12057 Berlin',st='S Sonnenallee',
      rolle='Deutschlands größtes Hotel ist Kulisse für illegale Pokerrunden und Clan-Treffen. Beim Pokerspiel gerät Toni unter Druck.',
      fig=['Toni'],staffel='S1',q=['yv','mv']),
 dict(id='private',n='Private Center Berlin',kat='justiz',geo='pt:private',kiez='Britz',
      adr='Britzer Damm 115, 12347 Berlin',st='U Blaschkoallee',
      rolle='Ausgerechnet ein Erotikkino: Hier trifft sich der verdeckte Ermittler Vince heimlich mit seinen Kontaktleuten von der Polizei.',
      fig=['Vince'],staffel='S1',q=['mv']),
 dict(id='kotti',n='Kottbusser Tor · Café Kotti',kat='revier',geo='pt:kotti',kiez='Kreuzberg',
      adr='Adalbertstraße 96 (Neues Kreuzberger Zentrum), 10999 Berlin',st='U Kottbusser Tor',
      rolle='Das Zentrum Kreuzbergs ist ein zentraler Handlungsort. Im Neuen Kreuzberger Zentrum liegt Vince’ Wohnung, im Café Kotti fliegt seine Tarnung als Undercover-Polizist auf.',
      tipp='Das Café Kotti im ersten Stock des NKZ ist ein echtes Café mit Blick auf den Platz.',
      fig=['Vince'],staffel='S1',q=['mv','sb','yv']),
 dict(id='goerli',n='Görlitzer Park',kat='revier',geo='area:Görlitzer Park',kiez='Kreuzberg',
      adr='Görlitzer Straße, 10997 Berlin',st='U Görlitzer Bahnhof · U Schlesisches Tor',
      rolle='Der „Görli“ ist das Revier der jüngeren Clan-Mitglieder Zeki und Issam für ihre Drogengeschäfte. Issam verliebt sich hier.',
      fig=['Zeki','Issam'],staffel='S1',q=['mv','sb','yv']),
 dict(id='daimler',n='Daimler Contemporary',kat='glamour',geo='pt:daimler',kiez='Tiergarten',
      adr='Alte Potsdamer Straße 5 (Haus Huth), 10785 Berlin',st='S+U Potsdamer Platz',
      rolle='Edle Kulisse im modernen Berlin: Auf der Dachterrasse finden geheime Treffen mit Lieferanten statt.',
      fig=['Toni'],staffel='S1',q=['mv','sb']),
 dict(id='jva',n='JVA Moabit',kat='justiz',geo='pt:jva',kiez='Moabit',
      adr='Alt-Moabit 12a, 10559 Berlin',st='U Turmstraße · S+U Hauptbahnhof',
      rolle='Tonis Schwager Latif landet hier nach der Razzia mit Kokain in Untersuchungshaft.',
      fig=['Latif'],staffel='S1',q=['mv']),
 dict(id='amtsgericht',n='Amtsgericht Tiergarten',kat='justiz',geo='pt:amtsgericht',kiez='Moabit',
      adr='Turmstraße 91, 10559 Berlin (Kriminalgericht Moabit)',st='U Turmstraße',
      rolle='Gerichtsszenen im wuchtigen Kriminalgericht: Abbas muss sich hier wegen Mordes verantworten.',
      alt='Mit Vergnügen nennt Turmstraße 92; das Gerichtsgebäude trägt die Hausnummer 91.',
      fig=['Abbas'],staffel='S2',q=['mv']),
]

FIG={
 'Toni':'Ali „Toni“ Hamady, Clanchef (Kida Khodr Ramadan)',
 'Vince':'Vince Kühn, verdeckter Ermittler (Frederick Lau)',
 'Abbas':'Abbas Hamady, Tonis Bruder (Veysel Gelin)',
 'Latif':'Latif, Tonis Schwager (Massiv)',
 'Kalila':'Kalila Hamady, Tonis Frau (Almila Bagriacik)',
 'Amara':'Amara',
 'Zeki':'Zeki, junges Clan-Mitglied',
 'Issam':'Issam, junges Clan-Mitglied',
}
KAT={
 'clan':['Clan & Familie','--k-clan'],
 'revier':['Reviere','--k-revier'],
 'justiz':['Polizei & Justiz','--k-justiz'],
 'glamour':['Deals in feiner Kulisse','--k-glamour'],
 'kiez':['Straßen & Kiez','--k-kiez'],
}
# Neukölln-Rundgang, zu Fuß
TOUR=['rathaus','teppich','blackwhite','elsalam','stuttgarter','estrel','highdeck']
